# Generated by Django 5.1.2 on 2024-11-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_buying', models.TextField()),
                ('payment_status', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('del_boy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rout', models.TextField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.IntegerField()),
                ('name', models.TextField()),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product_quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('shopid', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('password', models.IntegerField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shopreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('password', models.IntegerField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='delpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.TextField(null=True)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buy')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.delivery')),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shopreg'),
        ),
    ]
