# Generated by Django 5.0.1 on 2024-09-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buy_shopreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('shopid', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
