# Generated by Django 5.0.1 on 2024-11-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_register_password_alter_shopreg_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='del_boy',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='buy',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
