# Generated by Django 5.0.1 on 2024-11-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shopreg',
            name='password',
            field=models.TextField(),
        ),
    ]
