# Generated by Django 5.0.1 on 2024-09-16 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='delivery_not',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='productid',
        ),
        migrations.AddField(
            model_name='buy',
            name='del_boy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buy',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
    ]
