# Generated by Django 5.0.1 on 2024-09-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_buy_delivery_not_remove_buy_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date_of_buying',
            field=models.TextField(),
        ),
    ]
