# Generated by Django 5.0.1 on 2024-09-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_buy_date_of_buying'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rout', models.TextField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.IntegerField()),
                ('name', models.TextField()),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='delpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.TextField(null=True)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buy')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.delivery')),
            ],
        ),
    ]
