# Generated by Django 5.0.1 on 2024-09-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delivery_delpro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
